# Site settings
# These are used to personalize your new site.
title: Joshua Thomas Smith # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Technology in Computer-Science (class of 2021)
  <br /><br />
  <a href="/pdf/Smith Resume.pdf">View My Resume</a>
  [Reflection Questions](Smith Reflection Questions)
repository: "csci-csu/csci-portfolio"
github_username:  Joshtomith # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

